
pool:
  vmImage: windows-latest

steps:

- checkout: self
  clean: true
  persistCredentials: true

- task: BinSkim@4
  inputs:
    InputType: 'CommandLine'
    arguments: 'analyze $(Build.StagingDirectory)\* --recurse --verbose'

- task: CredScan@3
  inputs:
    outputFormat: 'csv'


- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'python'
    querySuite: 'Recommended'
    timeout: 1800
    ram: 16384
    addProjectDirToScanningExclusionList: true
  env:
      System_AccessToken: $(System.AccessToken)

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: PoliCheck@2
  inputs:
    targetType: 'F'
    targetArgument: '$(Build.SourcesDirectory)'


- task: VulnerabilityAssessment@0

- task: PublishSecurityAnalysisLogs@2

- task: PostAnalysis@1
  inputs:
    BinSkim: true
    CredScan: true
    Semmle: true

- download: current
  patterns: '**/*.json'

- download: current
  patterns: '**/*.xml'
